//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_FBCUSTOMFIELD_Epicare_Patient_History
    {
        public int ID { get; set; }
        public int Ptn_pk { get; set; }
        public int Visit_Pk { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> EPMotherAlive { get; set; }
        public string EPMothersName { get; set; }
        public Nullable<int> EPMothersAge { get; set; }
        public string EPMothersOccupation { get; set; }
        public Nullable<int> EPMothersMaritalStatus { get; set; }
        public Nullable<int> EPMothersEucation { get; set; }
        public Nullable<bool> EPFatherAlive { get; set; }
        public string EPFathersName { get; set; }
        public Nullable<int> EPFathersAge { get; set; }
        public string EPFathersOccupation { get; set; }
        public Nullable<int> EPFathersEducation { get; set; }
        public Nullable<bool> EPHistoryConvulsion { get; set; }
        public string EPHistoryRetardation { get; set; }
        public Nullable<int> EPPxBirthOrder { get; set; }
        public Nullable<int> EPMothersAgePxBirth { get; set; }
        public Nullable<bool> EPMotherSickDuringPregnancy { get; set; }
        public string EPDescribeSicknessDuringPregnancy { get; set; }
        public Nullable<int> EPDurationPregnancy { get; set; }
        public Nullable<int> EPMultipleBirth { get; set; }
        public Nullable<int> EPPlaceOfDelivery { get; set; }
        public Nullable<int> EPModeOfDelivery { get; set; }
        public Nullable<int> EPDurationOfDelivery { get; set; }
        public Nullable<int> EPSizeOfBaby { get; set; }
        public Nullable<int> EPWhatAge1stSeizure { get; set; }
        public string EPFullSeizureDescription { get; set; }
        public Nullable<bool> EPUnconsiousness { get; set; }
        public Nullable<bool> EPCloudingConsiousness { get; set; }
        public Nullable<bool> EPStiffness { get; set; }
        public Nullable<int> EPJerking { get; set; }
        public Nullable<bool> EPJerkingSmallMovements { get; set; }
        public Nullable<bool> EPNoMovementSloppyness { get; set; }
        public Nullable<bool> EPMainlyStrangeBehavior { get; set; }
        public Nullable<bool> EPDroolingSaliva { get; set; }
        public Nullable<bool> EPBittingTongue { get; set; }
        public Nullable<bool> EPIncontinenceStoolUrine { get; set; }
        public Nullable<bool> EPDoesPxKnowSeizureComing { get; set; }
        public string EPHowPxKnowsSeizureComing { get; set; }
        public Nullable<bool> EPAlwaysFeverWithSeizure { get; set; }
        public Nullable<bool> EPSeizureSameAsFirstAttack { get; set; }
        public Nullable<System.DateTime> EPWhenLastSeizure { get; set; }
        public Nullable<System.DateTime> EPWhenLastSeizureBeforeLast { get; set; }
        public Nullable<bool> EPSeizureConsecutiveDays { get; set; }
        public Nullable<bool> EPSeizuresRelatedNaturalEvents { get; set; }
        public Nullable<int> EPWhenSeizuresOccurMostly { get; set; }
        public Nullable<int> EPSmileMilestone { get; set; }
        public Nullable<decimal> EPCrawlMilestone { get; set; }
        public Nullable<int> EPSitMilestone { get; set; }
        public Nullable<int> EPStandMilestone { get; set; }
        public Nullable<int> EPWalkMilestone { get; set; }
        public Nullable<int> EPTalkMilestone { get; set; }
        public Nullable<int> EPFeedMilestone { get; set; }
        public Nullable<int> EPToiletTrainedMilestone { get; set; }
        public Nullable<bool> EPWeaknessLimbs { get; set; }
        public Nullable<bool> EPStiffnessLimbs { get; set; }
        public Nullable<bool> EPDoesPxSeeWell { get; set; }
        public Nullable<bool> EPDoesPxHearWell { get; set; }
        public Nullable<bool> EPDoesPxTalkWell { get; set; }
        public Nullable<int> EPPxMentalBehavior { get; set; }
        public Nullable<int> EPMentalRetardation { get; set; }
        public Nullable<int> EPImmunizationStatusChild { get; set; }
        public Nullable<int> EPDailyPxActivities { get; set; }
        public Nullable<int> EPReasonNoSchooling { get; set; }
        public Nullable<int> EPPxDailyActivitiesNotSchool { get; set; }
        public Nullable<bool> EPPxTraining { get; set; }
        public Nullable<bool> EPPxpaidforWork { get; set; }
        public Nullable<int> EPPxAdultFemalwithKids { get; set; }
        public Nullable<bool> EPPxCouncelledContraceptives { get; set; }
        public string EPHAdmissionReason { get; set; }
        public Nullable<int> EPIWhatAgeFirstSeizureMonths { get; set; }
        public string EPISeizureDiagnosisMore { get; set; }
    }
}
