//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class dtl_PatientPharmacyOrder
    {
        public int ptn_pharmacy_pk { get; set; }
        public int Drug_Pk { get; set; }
        public int GenericID { get; set; }
        public int StrengthID { get; set; }
        public Nullable<int> FrequencyID { get; set; }
        public Nullable<decimal> SingleDose { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<decimal> OrderedQuantity { get; set; }
        public Nullable<decimal> DispensedQuantity { get; set; }
        public Nullable<int> Financed { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> RegimenId { get; set; }
        public Nullable<int> Prophylaxis { get; set; }
        public Nullable<int> BatchNo { get; set; }
        public string TreatmentPhase { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<int> TabId { get; set; }
        public Nullable<int> PrintPrescriptionStatus { get; set; }
        public string PatientInstructions { get; set; }
        public int Id { get; set; }
        public string WhyPartial { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public Nullable<int> pillCount { get; set; }
    }
}
