//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class DTL_FBCUSTOMFIELD_Epicare
    {
        public int ID { get; set; }
        public int Ptn_pk { get; set; }
        public int Visit_Pk { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> NoANCVisits { get; set; }
        public string OtherImmunisation { get; set; }
        public Nullable<int> EPFUComplaints { get; set; }
        public string EPFUNoSeizuresSinceLastVisit { get; set; }
        public Nullable<bool> EPFUTakeMedsDaily { get; set; }
        public Nullable<int> EPFUHowManyTimesMissed { get; set; }
        public Nullable<int> EPFUTakeMedsPrescribedTime { get; set; }
        public Nullable<int> EPFUSeizuresAfterMissingMeds { get; set; }
        public string EpiComplaint { get; set; }
        public string EPFUSideEffectsOther { get; set; }
        public string EPFUDosingFrequency { get; set; }
    }
}
