//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mst_Drug
    {
        public int Drug_pk { get; set; }
        public string DrugID { get; set; }
        public int ItemTypeID { get; set; }
        public string DrugName { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<decimal> DispensingMargin { get; set; }
        public Nullable<decimal> DispensingUnitPrice { get; set; }
        public string FDACode { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<int> MaxStock { get; set; }
        public Nullable<int> MinStock { get; set; }
        public Nullable<decimal> PurchaseUnitPrice { get; set; }
        public Nullable<int> QtyPerPurchaseUnit { get; set; }
        public decimal SellingUnitPrice { get; set; }
        public Nullable<int> DispensingUnit { get; set; }
        public Nullable<int> PurchaseUnit { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int Sequence { get; set; }
        public string ItemInstructions { get; set; }
        public string Abbreviation { get; set; }
    }
}
