//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Collections.Generic;
    
    public partial class ord_PatientPharmacyOrder
    {
        public int ptn_pharmacy_pk { get; set; }
        public int Ptn_pk { get; set; }
        public Nullable<int> VisitID { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> OrderedBy { get; set; }
        public Nullable<System.DateTime> OrderedByDate { get; set; }
        public Nullable<int> DispensedBy { get; set; }
        public Nullable<System.DateTime> DispensedByDate { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> FDC { get; set; }
        public Nullable<int> ProgID { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> HoldMedicine { get; set; }
        public Nullable<int> Signature { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public Nullable<int> DeleteFlag { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> PharmacyPeriodTaken { get; set; }
        public Nullable<int> RegimenLine { get; set; }
        public string PharmacyNotes { get; set; }
        public Nullable<int> StoreId { get; set; }
        public Nullable<int> orderstatus { get; set; }
        public string ReportingID { get; set; }
        public Nullable<int> CPAD_PharmacyOrderId { get; set; }
        public Nullable<int> PatientMasterVisitId { get; set; }
        public Nullable<int> PatientId { get; set; }
    }
}
