//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaweCDMSMigration
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IQCareKAWEEntities : DbContext
    {
        public IQCareKAWEEntities()
            : base("name=IQCareKAWEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DTL_FBCUSTOMFIELD_Epicare> DTL_FBCUSTOMFIELD_Epicare { get; set; }
        public virtual DbSet<DTL_FBCUSTOMFIELD_Epicare_Patient_History> DTL_FBCUSTOMFIELD_Epicare_Patient_History { get; set; }
        public virtual DbSet<dtl_PatientAppointment> dtl_PatientAppointment { get; set; }
        public virtual DbSet<mst_User> mst_User { get; set; }
        public virtual DbSet<Mst_Drug> Mst_Drug { get; set; }
        public virtual DbSet<dtl_PatientPharmacyOrder> dtl_PatientPharmacyOrder { get; set; }
        public virtual DbSet<ord_PatientPharmacyOrder> ord_PatientPharmacyOrder { get; set; }
    
        public virtual ObjectResult<pr_PxMigration_Result> pr_PxMigration()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_PxMigration_Result>("pr_PxMigration");
        }
    }
}
